---
abstract: 'DB backend abstract class.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Put::Utils: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0
  Schema::Test: 0
  Test::MockObject: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Backend-DB
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Backend::DB::Transform: 0
  Class::Utils: 0
  Error::Pure: 0
  Scalar::Util: 0
  perl: 5.8.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Backend-DB/issues
  homepage: https://github.com/michal-josef-spacek/Backend-DB
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Backend-DB
version: '0.01'
